apiRules:
  - exclude:
      uidRegex: ^Fusee\.Example
      type: Type
  - exclude:
      uidRegex: ^Fusee\.Engine\.Player
      type: Type
  - exclude:
      uidRegex: ^Fusee\.Tools
      type: Type
  - exclude:
      uidRegex: Test$
      type: Type
